SELECT    A.USER_ID
        , A.NICKNAME
        , SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER A, USED_GOODS_BOARD B
WHERE A.USER_ID = B.WRITER_ID
AND STATUS = 'DONE'
GROUP BY A.USER_ID , A.NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES