

SELECT B.TITLE
,      B.BOARD_ID
,      R.REPLY_ID
,      R.WRITER_ID
,      R.CONTENTS
,      TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE --여기서는 r으로 조건처리하는거지 ?
FROM USED_GOODS_BOARD B JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
WHERE TO_CHAR(B.CREATED_DATE, 'YYYY-MM') = '2022-10' --왜 여기서는 b에 대해서 whwere 조건처리하고 
ORDER BY R.CREATED_DATE, B.TITLE; 